# Generated by Django 3.0.7 on 2020-12-19 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='EmpDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_fname', models.CharField(max_length=256)),
                ('emp_midname', models.CharField(max_length=256)),
                ('emp_lastname', models.CharField(max_length=256)),
                ('gender', models.CharField(max_length=1)),
                ('dob', models.DateField()),
                ('mob_no', models.IntegerField()),
                ('alt_mob_no', models.IntegerField()),
                ('emp_marital_stat', models.CharField(max_length=10)),
                ('blood_grp', models.CharField(max_length=5)),
                ('emp_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empManager.EmpLogin')),
            ],
        ),
    ]
