# Generated by Django 3.0.7 on 2020-12-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empManager', '0002_remove_empdetails_alt_mob_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='empdetails',
            name='alt_mob_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
