# Generated by Django 3.0.7 on 2020-12-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empManager', '0003_empdetails_alt_mob_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdetails',
            name='alt_mob_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='empdetails',
            name='mob_no',
            field=models.CharField(max_length=10),
        ),
    ]
